export default {
  validations: {
    sizeRequired: "Please choose an available size.",
    emailRequired: "Please enter an email address.",
    emailValid: "Must be a valid email address.",
    emailExistsPartOne: "An account with email",
    emailExistsPartTwo: "already exists.",
    passwordRequired: "Please enter a password.",
    passwordMatch:
      "Must contain at least 8 characters, one uppercase letter, one lowercase letter and one number.",
    avatarRequired: "Please select an avatar.",
    usernameRequired: "Please include a username.",
    usernameMin: "Must be at least 3 characters long.",
    usernameMax: "Must be 20 or less characters long.",
    usernameMatch: "Cannot contain spaces.",
    countryRequired: "Please select a country.",
    shippingRequired: "Please select a shipping option.",
    yourEmailValid: "Please include your email address.",
    firstNameRequired: "Please include your first name.",
    lastNameRequired: "Please include your last name.",
    addressRequired: "Please include your address.",
    quizNameRequired: "Please enter a name for your quiz.",
    quizIsPublicRequired:
      "Please choose whether your quiz will be public or private.",
    quizQuestionsMin: "Must include at least one question.",
    quizTypeRequired: "Please select a quiz type.",
    questionRequired: "Please enter a value for question.",
    answersMin: "Must include at least two answers.",
    correctAnswerRequired: "Please select a correct answer.",
    imageUrlRequired:
      "Must include imageUrl for image questions. Please search for an image and select one of the options below.",
    flagCodeRequired: "Must include flagCode for flag questions.",
    mapRequired: "Must include map for map questions.",
    flagGroupLabelRequired: "Please enter a flag group label.",
    mappingKeyRequired: "Please select a mapping key.",
    flagEntryCodeRequired: "Please enter a code for flag entry.",
    flagEntryUrlRequired: "Please enter a url for flag entry.",
    mappingLabelRequired: "Please enter a group label.",
    mappingEntryNameRequired: "Please enter a name for mapping entry.",
    mappingEntryCodeRequired: "Please enter a code for mapping entry.",
    mappingEntrySVGNameRequired: "Please enter a svg name for mapping entry.",
  },
  shoppingCart: {
    continueShopping: "Continue Shopping",
    emptyAlert: "Your cart is empty.",
    invalidDiscountCodeAlert: "Invalid discount code. Please try again.",
    invalidItemAlert:
      "Discount code does not apply to any of the items in this cart. Please try again.",
    successAlert: "Successfully applied discount code",
    errorAlert: "Error applying discount code. Please try again.",
  },
};
